import "./globals.css";
import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import { Providers } from "./providers";
import NavigationBar from "@/components/navbar";
import Image from "next/image";
import Link from "next/link";

const poppins = Poppins({ subsets: ["latin"], weight: "400" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="dark text-foreground bg-background">
      <body className={poppins.className}>
        <Providers>
          <NavigationBar />
          <Link href="/">
            <div className="flex justify-center p-4">
              <Image
                src="/img/pokedex.png"
                alt="pokedex logo"
                width="200"
                height="200"
              />
            </div>
          </Link>
          {children}
        </Providers>
      </body>
    </html>
  );
}
